version: '3'
services:
  node:
    restart: always
    build: .
    ports:
      - 80:3000
    networks:
      - default
    volumes:
      - ./:/code
    depends_on:
      - mongo

  mongo:
    image: mongo
    command: mongod --port 27018
    networks:
      - default
    ports:
      - 27018:27018
    volumes:
      - mongodb:/data/db


networks:
  default:
    ipam:
      config:
        - subnet: 172.18.1.0/24

volumes:
 mongodb:
