const express = require('express')
const app = express()
const expressip = require('express-ip')
const http = require('http').createServer(app)
const io = require('socket.io')(http)
const bodyParser = require('body-parser')
const path = require('path')
const env = require('dotenv')
const cors = require('cors')
env.config()
global.appRoot = path.resolve(__dirname)
app.use(expressip().getIpInfoMiddleware)
app.use(express.json({limit: '50mb'}))
app.use(express.urlencoded({limit: '50mb'}))
app.use(bodyParser.urlencoded({extended: false}))
app.use(bodyParser.json())
app.use(cors())
app.use('/static', express.static(__dirname + '/public'))
app.use(cors({origin: '*'}))
app.use(express.json())
const routes = require('./src/routes/routes')
routes(app)
http.listen(process.env.WEB_SERVER_PORT_INT, "0.0.0.0", function () {
    console.log('Listening on port ' + process.env.WEB_SERVER_PORT_INT)
})
