# When deploying to a production environment, please refer to the Helm Repository
# for FIWARE Components in order to scale up to a proper architecture:
# see: https://github.com/FIWARE/helm-charts/

version: "3.9"
services:
  # Orion is the context broker
  orion:
    init: true
    restart: always
    image: fiware/orion:3.10.1              # This variable `${ORION_VERSION}` is drawn from the `.env` file
    hostname: orion                        # Container's name within the network (e.g., `ping orion` is a valid command)
    container_name: orion                  # Name of the created container (e.g., `docker exec -it orion /bin/bash` or `docker logs orion`)
    depends_on:
      - mongo-db                           # Create the `mongo-db` before this container
    networks:
      - default                            # Name of the Docker network
    ports:
      - "${ORION_PORT_EXT}:${ORION_PORT_INT}"  # Map a local port to a container's port (e.g., `IP:8082` to `IP:1026`)
    # Append this string to the final command that is executed by the container
    # Here, we are launching the OCB with: the possibility to perform "cors" requests, the name of the database, and the maximum payload parameter
    # You can also set the log level by adding `-logLevel DEBUG`
    command: -corsOrigin __ALL -dbhost mongo-db -inReqPayloadMaxSize ${ORION_MAX_PAYLOAD}
    healthcheck: # Every 5seconds do a request to the OCB to ensure that the OCB is running
      # test: curl --fail -s http://${ORION_IP}:${ORION_PORT_EXT}/version
      test: curl --fail -s http://${ORION_IP}:${ORION_PORT_EXT}/v2/entities?options=keyValues&limit=1 #
      interval: 5s
      timeout: 10s

  iot-agent:
    init: true
    restart: always
    image: ${SWARM_REGISTER_IP}:${SWARM_REGISTER_PORT}/iot-agent
    build:
      context: ./devices
      dockerfile: iota.Dockerfile
    hostname: iot-agent
    container_name: iot-agent
    depends_on:
      - mosquitto
    networks:
      - default
    ports:
      - "${IOTA_PORT_EXT}:${IOTA_PORT_EXT}"
    healthcheck:
      test: curl --fail -s http://localhost:${IOTA_PORT_EXT}
      interval: 5s
      timeout: 10s

  # Database (orion + persistence)
  mongo-db:
    init: true
    restart: always
    image: mongo:6.0
    hostname: mongo-db
    container_name: mongo-db
    ports:
      - "${MONGO_DB_PERS_PORT_EXT}:27017"
    networks:
      - default
    volumes:
      - ${SWARM_NFS}/mongodb:/data/db
    healthcheck:
      test: |
        host=`hostname --ip-address || echo '127.0.0.1'`;
        mongo --quiet $${host}/test --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)' && echo 0 || echo 1
      interval: 5s
      timeout: 10s

  # MQTT Broker
  mosquitto:
    init: true
    image: eclipse-mosquitto:2.0.11
    hostname: mosquitto
    container_name: mosquitto
    ports:
      - "${MOSQUITTO_PORT_EXT}:1883"
      - "${MOSQUITTO_PORT_EXT_TLS}:8883"
    volumes:
      - ${SWARM_NFS}/mosquitto/config:/mosquitto/config:ro
      - ${SWARM_NFS}/mosquitto/log:/mosquitto/log
      - ${SWARM_NFS}/mosquitto/data:/mosquitto/data
    networks:
      - default

  # Web server
  nodews:
    init: true
    restart: always
    hostname: nodews
    container_name: nodews
    image: ${SWARM_REGISTER_IP}:${SWARM_REGISTER_PORT}/nodews
    build: ./service-dashboard
    ports:
      - "${WEB_SERVER_PORT_EXT}:${WEB_SERVER_PORT_INT}"
    networks:
      - default
    env_file:
      - .env
    healthcheck:
      test: curl --fail -s http://localhost:${WEB_SERVER_PORT_INT}
      interval: 5s
      timeout: 10s

  portainer:
    init: true
    hostname: portainer
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - 9443:9443
    volumes:
      - ${SWARM_NFS}/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    deploy:
      placement:
        constraints:
          - node.labels.role==master

  etl:
    init: true
    hostname: etl
    image: ${SWARM_REGISTER_IP}:${SWARM_REGISTER_PORT}/etl
    build: ./etl
    container_name: etl
    ports:
      - "${DRACO_PORT_EXT}:${DRACO_PORT_EXT}"
    networks:
      - default
    env_file:
      - .env
    healthcheck:
      test: |
        curl --fail -H 'Content-Type: application/json' -d '{"heartbeat": ""}' -s http://localhost:${DRACO_PORT_EXT}
      interval: 5s
      timeout: 10s

  missionsupervisor:
    init: true
    hostname: missionsupervisor
    image: ${SWARM_REGISTER_IP}:${SWARM_REGISTER_PORT}/missionsupervisor
    build: ./service-missionsupervisor
    container_name: missionsupervisor
    ports:
      - "${SUPERVISOR_PORT_EXT}:${SUPERVISOR_PORT_EXT}"
    networks:
      - default
    env_file:
      - .env
    healthcheck:
      test: |
        curl --fail -H 'Content-Type: application/json' -d '{"heartbeat": ""}' -s http://localhost:${SUPERVISOR_PORT_EXT}
      interval: 5s
      timeout: 10s

  missionplanner:
    init: true
    hostname: missionplanner
    image: ${SWARM_REGISTER_IP}:${SWARM_REGISTER_PORT}/missionplanner
    build: ./service-missionplanner
    container_name: missionplanner
    ports:
      - "${PLANNER_PORT_EXT}:${PLANNER_PORT_EXT}"
    networks:
      - default
    env_file:
      - .env
    healthcheck:
      test: |
        curl --fail -H 'Content-Type: application/json' -d '{"heartbeat": ""}' -s http://localhost:${PLANNER_PORT_EXT}
      interval: 5s
      timeout: 10s

  mapbuilder:
    init: true
    hostname: mapbuilder
    image: ${SWARM_REGISTER_IP}:${SWARM_REGISTER_PORT}/mapbuilder
    build: ./service-mapbuilder
    container_name: mapbuilder
    ports:
      - "${BUILDER_PORT_EXT}:${BUILDER_PORT_EXT}"
    networks:
      - default
    env_file:
      - .env
    healthcheck:
      test: |
        curl --fail -H 'Content-Type: application/json' -d '{"heartbeat": ""}' -s http://localhost:${BUILDER_PORT_EXT}
      interval: 5s
      timeout: 10s

  kafkaproxy:
    init: true
    restart: always
    hostname: kafkaproxy
    image: ${SWARM_REGISTER_IP}:${SWARM_REGISTER_PORT}/kafkaproxy
    container_name: kafkaproxy
    build: ./service-kafkaproxy
    ports:
      - "${PROXY_PORT_EXT}:${PROXY_PORT_INT}"
    networks:
      - default
    env_file:
      - .env
    healthcheck:
      test: npm test
      interval: 60s
      timeout: 60s

  writeimages:
    init: true
    restart: always
    hostname: writeimages
    image: ${SWARM_REGISTER_IP}:${SWARM_REGISTER_PORT}/writeimages
    build:
      context: ./devices
      dockerfile: writeimages.Dockerfile
    container_name: writeimages
    networks:
      - default
    env_file:
      - .env
    volumes:
      - ${SWARM_NFS}/images-dump:/usr/src/myapp/resources/ftpimages

  writetomongo:
    init: true
    restart: always
    hostname: writetomongo
    image: ${SWARM_REGISTER_IP}:${SWARM_REGISTER_PORT}/writetomongo
    build:
      context: ./devices
      dockerfile: writetomongo.Dockerfile
    container_name: writetomongo
    networks:
      - default
    env_file:
      - .env
    depends_on:
      - mongo-db

  device-python:
    init: true
    hostname: device-python
    build: ./devices-python
    image: ${SWARM_REGISTER_IP}:${SWARM_REGISTER_PORT}/device-python
    container_name: device-python
    networks:
      - default
    env_file:
      - .env
    ports:
      - "12346-13000:12346-13000"

  nginx:
    hostname: nginx
    container_name: nginx
    init: true
    restart: always
    image: jetbrainsinfra/nginx-file-listing:0.2 # nginx:1.23.2
    ports:
      - "${IMAGESERVER_PORT_HTTP_EXT}:80"
      # - "${IMAGESERVER_PORT_HTTPS_EXT}:443"
    volumes:
      - "${SWARM_NFS}/images-dump:/mnt/data"
    # healthcheck:
    #   test: curl --fail -s http://localhost:80
    #   interval: 5s
    #   timeout: 10s

  ftp:
    hostname: ftp
    container_name: ftp
    init: true
    restart: always
    image: stilliard/pure-ftpd
    environment:
      FTP_USER_NAME: "${IMAGESERVER_USER}"
      FTP_USER_PASS: "${IMAGESERVER_PWD}"
      FTP_USER_HOME: "/data"
      FTP_PASSIVE_PORTS: "${IMAGESERVER_PORT_FTP_MIN}:${IMAGESERVER_PORT_FTP_MAX}"
      FTP_MAX_CLIENTS: 50
      FTP_MAX_CONNECTIONS: 20
      ADDED_FLAGS: "-d -d"
      PUBLICHOST: "${IMAGESERVER_IP}"
    volumes:
      - "${SWARM_NFS}/images-dump:/data"
    ports:
      - "${IMAGESERVER_PORT_FTP20_EXT}:20"
      - "${IMAGESERVER_PORT_FTP21_EXT}:21"
      - "${IMAGESERVER_PORT_FTP_MIN}-${IMAGESERVER_PORT_FTP_MAX}:${IMAGESERVER_PORT_FTP_MIN}-${IMAGESERVER_PORT_FTP_MAX}/tcp"
    # healthcheck:
    #   test: wget -O .dummy ftp://${IMAGESERVER_USER}:${IMAGESERVER_PWD}@localhost:21/.dummy
    #   interval: 5s
    #   timeout: 10s

networks:
  default_net:
    ipam:
      config:
        - subnet: 172.18.1.0/24
