version: "3.9"
services:
  zookeeper:
    hostname: zookeeper
    container_name: zookeeper
    init: true
    image: wurstmeister/zookeeper
    ports:
      - "${ZOOKEEPER_PORT_EXT}:2181"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafka:
    hostname: kafka
    container_name: kafka
    init: true
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "${KAFKA_PORT_EXT}:9092"
    environment:
      DOCKER_API_VERSION: 1.22
      KAFKA_ADVERTISED_HOST_NAME: ${KAFKA_IP}
      KAFKA_ZOOKEEPER_CONNECT: ${ZOOKEEPER_IP}:${ZOOKEEPER_PORT_EXT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
