package it.unibo

const val AGRI_FARM = "urn:ngsi-ld:AgriFarm:6991ac61-8db8-4a32-8fef-c462e2369055"
const val AGRI_ROBOT = "AgriRobot"
const val AREA_SERVED = "areaServed"
const val CMD = "cmd"
const val CMD_LIST = "cmdList"
const val COORDINATES = "coordinates"
const val DATA_MODEL_FOLDER = "/datamodels/$AGRI_FARM"
const val DOMAIN = "domain"
const val FARM_LATITUDE = 40.3123117652
const val FARM_LONGITUDE = -3.481042237784
const val HEARTBEAT = "heartbeat"
const val HUMIDITY = "humidity"
const val IMAGE = "image"
const val LOCATION = "location"
const val TEMPERATURE = "temperature"
const val TIMESTAMP = "timestamp"
const val TYPE = "type"
const val ROBOT_CMD_PAUSE = "pause"
const val ROBOT_CMD_RESUME = "resume"
const val ROBOT_CMD_START = "execute_mission"
const val ROBOT_CMD_STOP = "abort"
const val MISSION_FILE = "Mission.json"
const val MISSION_ID = "urn:ngsi-ld:Task:01f237b6-09df-42dc-b84a-8e2091e840f0"
const val ROBOT_FILE = "carob-1.json"
const val ROBOT_ID = "carob-1"