name: "Build"
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
        with:
          submodules: recursive
          fetch-depth: 0
          ssh-key: ${{secrets.KEY}}
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Launch and test
        run: |
          cd welaser
          for i in $(seq 2)
          do
            echo "Run $i"
            scripts/config.sh
            ./launch.sh -ts
            scripts/mongodb-dump.sh
            ./stop.sh
          done
  release:
    needs:
      - build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Release
        run: |
          npm install
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
