name: "Build"
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['11'] # , '14'
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          submodules: recursive
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8.10'
          architecture: 'x64'
      - name: Launch and test
        run: |
          cd welaser
          scripts/config.sh
          ./launch.sh
          pip install -r testScripts/requirements.txt
          scripts/runTests.sh
          scripts/mongodb-dum.sh
      - name: Stop
        run: |
          cd welaser
          ./stop.sh
  release:
    needs:
      - build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Release
        run: |
          npm install
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
