version: "3.9"
services:
  zookeeper:
    hostname: zookeeper
    container_name: zookeeper
    init: true
    image: wurstmeister/zookeeper
    ports:
      - "${ZOOKEEPER_PORT_EXT}:2181"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - welaser-network

  kafka:
    hostname: kafka
    container_name: kafka
    init: true
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "${KAFKA_PORT_EXT}:9092"
    environment:
      DOCKER_API_VERSION: 1.22
      KAFKA_ADVERTISED_HOST_NAME: "${KAFKA_IP}"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "${DRACO_RAW_TOPIC}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - welaser-network

networks:
  welaser-network:
    name: welaser-network
    driver: bridge
